'use client'
export const dynamic = 'error'
import { useEffect } from 'react'
import { ScrollSpyProvider } from '@/components/ScrollSpyProvider'
import { SectionPager } from '@/components/SectionPager'
import { SiteHeader } from '@/components/SiteHeader'
import { Hero } from '@/components/Hero'
import { WhyMugen } from '@/components/WhyMugen'
import { Industries } from '@/components/Industries'
import { Services } from '@/components/Services'
import { About } from '@/components/About'
import { Contact } from '@/components/Contact'
import { Footer } from '@/components/Footer'
import { BackToTop } from '@/components/BackToTop'
export default function Page(){ useEffect(()=>{ const onClick=(e:MouseEvent)=>{ const a=(e.target as HTMLElement).closest('a'); if(a && a instanceof HTMLAnchorElement && a.hash && a.getAttribute('href')?.startsWith('#')){ const id=a.hash.slice(1); const el=document.getElementById(id); if(el){ e.preventDefault(); el.scrollIntoView({behavior:'smooth', block:'start'}); history.replaceState(null,'',`#${id}`) }}}; document.addEventListener('click', onClick); return ()=>document.removeEventListener('click', onClick)},[]); const sections=['home','services','about','contact']; return (<ScrollSpyProvider sectionIds={sections}><SiteHeader/><main><Hero/><div className="divider" /><WhyMugen/><div className="divider" /><Industries/><div className="divider" /><Services/><div className="divider" /><About/><div className="divider" /><Contact/></main><Footer/><BackToTop/><SectionPager ids={sections}/></ScrollSpyProvider>) }
